# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-08 19:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FOO_BAR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foo', models.CharField(default='foo', max_length=32, verbose_name='foo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foo_bar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
