# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-08 19:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.IntegerField(unique=True, verbose_name='Permit Number')),
                ('master_use_permit', models.IntegerField(blank=True, null=True, verbose_name='Master Use Permit')),
                ('action_type', models.CharField(blank=True, max_length=25, null=True, verbose_name='Action Type')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address')),
                ('applicant_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Applicant Name')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('date_modified', models.DateField(auto_now=True, verbose_name='Date Modified')),
                ('application_date', models.DateTimeField(blank=True, null=True, verbose_name='Application Date')),
                ('issue_date', models.DateTimeField(blank=True, null=True, verbose_name='Issue Date')),
                ('final_date', models.DateTimeField(blank=True, null=True, verbose_name='Final Date')),
                ('experation_date', models.DateTimeField(blank=True, null=True, verbose_name='Experation Date')),
                ('category', models.CharField(blank=True, max_length=24, null=True, verbose_name='Category')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('latitude', models.FloatField(blank=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, verbose_name='Longitude')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('permit_type', models.CharField(blank=True, max_length=24, null=True, verbose_name='Type')),
                ('status', models.CharField(blank=True, max_length=55, null=True, verbose_name='Status')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Value')),
                ('work_type', models.CharField(blank=True, max_length=24, null=True, verbose_name='Work Type')),
                ('contractor', models.CharField(blank=True, max_length=128, null=True, verbose_name='Contractor')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
